### ISSUE TITLE
Is the project still functional!

### ISSUE THREAD

**Issue by srijanshetty** [tj/mon#49]
I really love the project and wanted to know about the state of maintenance.

**Comment by Marak** [comment]
I'm using `mon` across hundreds of production servers at this exact moment.

I hope it's still functional. If anyone can prove otherwise please let us know.

**Comment by tj** [comment]
@srijanshetty should be fine, try it out 😄 C doesn't really change much. Might be better off just using systemd these days or Docker etc

**Comment by srijanshetty** [comment]
@tj it's functional for sure. Just wanted to make sure that you're around if the need ever arises :)

Systemd - I've used systemd before and it doesn't scale very well with the number of jobs you want to use.

Docker - KISS. Don't see the need of docker yet.
